"""
schemas.py — Pydantic data models for the ClauseGuard DSPy pipeline.

This module defines:
  - ClauseInput:         Mirrors Developer 1's parsed_clauses handoff schema.
  - ClauseAnalysisResult: The output produced by the DSPy pipeline per clause.

These are intentionally decoupled from the SQLAlchemy ORM models (models.py)
so that the DSPy layer can be developed and tested independently of the DB.
"""

from __future__ import annotations

from typing import Literal, Optional
from uuid import UUID

from pydantic import BaseModel, Field

RiskLevel = Literal["low", "medium", "high"]


class ClauseInput(BaseModel):
    """
    Represents a single parsed clause received from Developer 1's handoff.

    Fields map 1:1 to the JSON response of POST /api/contracts/upload,
    specifically each item in the ``parsed_clauses`` array.
    """

    parsed_clause_id: UUID = Field(
        ...,
        description="Primary key of the ParsedClause row in the DB.",
    )
    contract_id: UUID = Field(
        ...,
        description="FK referencing the parent Contract row.",
    )
    raw_text: str = Field(
        ...,
        description="Original clause text extracted from the PDF.",
    )
    clause_type: str = Field(
        ...,
        description=(
            "ML-predicted clause category. "
            "One of: ip_assignment, payment_terms, termination, liability, "
            "confidentiality, scope_of_work, governing_law, general."
        ),
    )
    clause_type_confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description=(
            "Platt-calibrated max class probability from the Layer 1 "
            "classifier, in [0, 1]. Below 0.40 the clause_type is overridden "
            "to 'general' upstream; the original probability is preserved here."
        ),
    )


class ClauseAnalysisResult(BaseModel):
    """
    The enriched output produced by the DSPy pipeline for a single clause.

    This is what Developer 1 will eventually pull from the ``risk_scores``
    table (via the ``plain_language_summary`` column) to render in the
    Next.js frontend.
    """

    parsed_clause_id: UUID = Field(
        ...,
        description="Echo of the input parsed_clause_id for traceability.",
    )
    contract_id: UUID = Field(
        ...,
        description="Echo of the input contract_id for traceability.",
    )
    clause_type: str = Field(
        ...,
        description="Echo of the input clause_type for reference.",
    )
    clause_type_confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description=(
            "Echo of the L1 classifier confidence so that downstream scoring "
            "(Layer 3 hybrid) can blend L1 + L2 signals without re-querying."
        ),
    )
    plain_language_summary: str = Field(
        ...,
        description=(
            "A plain-English explanation of what this clause means for the user. "
            "Generated by the DSPy ChainOfThought module."
        ),
    )
    risk_factors: list[str] = Field(
        ...,
        description="A list of specific reasons why the clause might be problematic.",
    )
    dspy_risk_score: float = Field(
        ...,
        description="A numeric score between 0.0 and 1.0 representing the AI's assessment of the risk.",
    )
    risk_level: str = Field(
        ...,
        description=(
            "Derived risk level: 'low', 'medium', or 'high'. "
            "Based on the dspy_risk_score."
        ),
    )


# ---------------------------------------------------------------------------
# GET /api/contracts/{id}/results — read envelope
# ---------------------------------------------------------------------------

class ClauseResult(BaseModel):
    """One clause as exposed by the read endpoint.

    L1 fields are always present. L2/L3 fields are None when the DSPy pipeline
    has not yet produced a risk_scores row for this clause.
    """

    parsed_clause_id: UUID
    contract_id: UUID
    clause_index: int
    raw_text: str
    clause_type: str
    clause_type_confidence: float

    plain_language_summary: Optional[str] = None
    risk_factors: Optional[list[str]] = None
    dspy_risk_score: Optional[float] = None
    risk_level: Optional[RiskLevel] = None  # hybrid (L3)


class ContractResultsResponse(BaseModel):
    status: Literal["success", "error"]
    contract_id: UUID
    filename: str
    clauses: list[ClauseResult]
    disclaimer: str
    detail: Optional[str] = None
