"""
schemas.py — Pydantic data models for the ClauseGuard DSPy pipeline.

This module defines:
  - ClauseInput:         Mirrors Developer 1's parsed_clauses handoff schema.
  - ClauseAnalysisResult: The output produced by the DSPy pipeline per clause.

These are intentionally decoupled from the SQLAlchemy ORM models (models.py)
so that the DSPy layer can be developed and tested independently of the DB.
"""

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, Field


class ClauseInput(BaseModel):
    """
    Represents a single parsed clause received from Developer 1's handoff.

    Fields map 1:1 to the JSON response of POST /api/contracts/upload,
    specifically each item in the ``parsed_clauses`` array.
    """

    parsed_clause_id: UUID = Field(
        ...,
        description="Primary key of the ParsedClause row in the DB.",
    )
    contract_id: UUID = Field(
        ...,
        description="FK referencing the parent Contract row.",
    )
    raw_text: str = Field(
        ...,
        description="Original clause text extracted from the PDF.",
    )
    clause_type: str = Field(
        ...,
        description=(
            "ML-predicted clause category. "
            "One of: ip_assignment, payment_terms, termination, liability, "
            "confidentiality, scope_of_work, governing_law, general."
        ),
    )


class ClauseAnalysisResult(BaseModel):
    """
    The enriched output produced by the DSPy pipeline for a single clause.

    This is what Developer 1 will eventually pull from the ``risk_scores``
    table (via the ``plain_language_summary`` column) to render in the
    Next.js frontend.
    """

    parsed_clause_id: UUID = Field(
        ...,
        description="Echo of the input parsed_clause_id for traceability.",
    )
    contract_id: UUID = Field(
        ...,
        description="Echo of the input contract_id for traceability.",
    )
    clause_type: str = Field(
        ...,
        description="Echo of the input clause_type for reference.",
    )
    plain_language_summary: str = Field(
        ...,
        description=(
            "A plain-English explanation of what this clause means for the user. "
            "Generated by the DSPy ChainOfThought module."
        ),
    )
    initial_risk_assessment: str = Field(
        ...,
        description=(
            "Initial risk level: 'low', 'medium', or 'high'. "
            "Generated by the DSPy ChainOfThought module."
        ),
    )
