"""disclaimer logs

Revision ID: 8bcac6357f9b
Revises: dc5e89922cd3
Create Date: 2026-08-20 11:00:58.915108

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bcac6357f9b'
down_revision = 'dc5e89922cd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disclaimer_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('page', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disclaimer_logs_created_at'), 'disclaimer_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disclaimer_logs_created_at'), table_name='disclaimer_logs')
    op.drop_table('disclaimer_logs')
    # ### end Alembic commands ###
