"""contract findings and executive summary

Revision ID: dc5e89922cd3
Revises: 90ecfb7b9b97
Create Date: 2026-08-20 10:50:14.315830

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc5e89922cd3'
down_revision = '90ecfb7b9b97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('finding_type', sa.String(length=32), nullable=False),
    sa.Column('pain_point', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_findings_contract_id'), 'contract_findings', ['contract_id'], unique=False)
    op.add_column('contracts', sa.Column('analysis_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'analysis_summary')
    op.drop_index(op.f('ix_contract_findings_contract_id'), table_name='contract_findings')
    op.drop_table('contract_findings')
    # ### end Alembic commands ###
