"""baseline schema

Revision ID: 1140f40c90e2
Revises: 
Create Date: 2026-08-20 10:22:36.754390

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1140f40c90e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_created_at'), 'contracts', ['created_at'], unique=False)
    op.create_table('parsed_clauses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('clause_index', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('clause_type', sa.String(length=128), nullable=True),
    sa.Column('clause_type_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsed_clauses_contract_id'), 'parsed_clauses', ['contract_id'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parsed_clause_id', sa.UUID(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('risk_percentile', sa.Integer(), nullable=True),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('plain_language_summary', sa.Text(), nullable=True),
    sa.Column('ml_model_version_id', sa.UUID(), nullable=True),
    sa.Column('dspy_program_version', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parsed_clause_id'], ['parsed_clauses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parsed_clause_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_parsed_clauses_contract_id'), table_name='parsed_clauses')
    op.drop_table('parsed_clauses')
    op.drop_index(op.f('ix_contracts_created_at'), table_name='contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
